source 'https://github.com/CocoaPods/Specs.git'

target 'AfterShipKit_Example', :exclusive => true do
  pod 'AfterShipKit', :path => '../'
end

target 'AfterShipKit_Tests', :exclusive => true do
  pod 'AfterShipKit', :path => '../'
  pod 'OHHTTPStubs'
end
