# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode7.2
cache: cocoapods
rvm: 2.2.2
podfile: Example/Podfile
xcode_workspace: Example/AfterShipKit.xcworkspace
xcode_scheme: AfterShipKit-Example
before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod install --project-directory=Example
script:
- pod lib lint
